name: Test app

on: pull_request

jobs:
  Test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'
          
      - name: Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.4.2
          virtualenvs-create: true
          virtualenvs-in-project: true
          
      - name: Install dependencies
        working-directory: ./project
        run: poetry install --no-root --no-dev
        
      - name: Run tests
        working-directory: ./project
        run: |
          poetry run python manage.py migrate
          poetry run python manage.py test
      

